export const menu = [
    {
        id: 1,
        name: "Espresso",
        tagline: "The soul of coffee",
        price: 3.5,
        logo: "☕",
        desc: "Double shot, rich crema, bold and unapologetic.",
        color: "#4A1E00",
    },
    {
        id: 2,
        name: "Flat White",
        tagline: "Silk in a cup",
        price: 5.0,
        logo: "🥛",
        desc: "Velvety microfoam over a ristretto base.",
        color: "#3B2A14",
    },
    {
        id: 3,
        name: "Cold Brew",
        tagline: "Patience, rewarded",
        price: 5.5,
        logo: "🧊",
        desc: "24-hour steep. Smooth, low acidity, naturally sweet.",
        color: "#0D1A2B",
    },
    {
        id: 4,
        name: "Cortado",
        tagline: "Spanish precision",
        price: 4.5,
        logo: "🍵",
        desc: "Equal parts espresso and warm milk. Perfectly balanced.",
        color: "#2E1A00",
    },
    {
        id: 5,
        name: "Matcha Latte",
        tagline: "The quiet rebel",
        price: 5.5,
        logo: "🍵",
        desc: "Ceremonial grade matcha, steamed oat milk, earthy calm.",
        color: "#0D2010",
    },
    {
        id: 6,
        name: "Pour Over",
        tagline: "Ritual brewing",
        price: 6.0,
        logo: "🫖",
        desc: "Single origin, bloom & pour, 3-minute meditative craft.",
        color: "#1E1200",
    },
];